env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - id: "main-build"
    main: ./cmd/helm-variable-in-values
    binary: ./bin/helm-viv
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
      - "386"
    goarm:
      - "6"
      - "7"
    ldflags:
      - "-s -w"
      - "-X {{ .ModulePath }}/common.version={{ .Version }}"
      - "-X {{ .ModulePath }}/common.buildDate={{ .Date }}"
      - "-X {{ .ModulePath }}/common.gitCommit={{ .ShortCommit }}"
      - "-X {{ .ModulePath }}/common.gitTreeState=clean"
      - "-X {{ .ModulePath }}/common.gitTag={{ .Tag }}"
    hooks:
      post:
        - ./scripts/compress.sh
archives:
  - id: tarball
    format: tar.gz
    name_template: '{{ .Os }}_{{ .Arch }}{{ if .Arm }}_v{{ .Arm }}{{ end }}'
    files:
      - LICENSE
      - plugin.yaml
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      amd64: 64-bit
      386: 32-bit
      arm: ARM
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows
      openbsd: OpenBSD
      netbsd: NetBSD
      freebsd: FreeBSD