name: build

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup go environment
        uses: actions/setup-go@v1
        with:
          go-version: '1.18'
      - name: setup-yq
        uses: chrisdickinson/setup-yq@v1.0.0
        with:
          yq-version: v4.25.3
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: build binary
        run: make build_linux link_linux